### ISSUE TITLE
a javascrip error 뭐시기

### ISSUE THREAD

**Issue by newhajinyoon** [dodo1120/entry-builder#2]
![image](https://user-images.githubusercontent.com/61103309/187236568-a023febb-493f-4a8c-832b-d2f43f714ba9.png)

**Comment by MineDora1120** [comment]
__dirname을 쓰셔야 합니다.

![화면 캡처 2022-09-09 204234](https://user-images.githubusercontent.com/62548380/189342424-0ffae1c0-731f-4175-a6ee-831093544da6.png)
